export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return <div className="dashboard-wrapper">{children}</div>;
}
